
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author success
 */
public class BookListScienceR extends javax.swing.JFrame {

    /**
     * Creates new form BookListScienceR
     */
    public BookListScienceR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbio = new javax.swing.JTextField();
        rphy = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        engr = new javax.swing.JCheckBox();
        Smathr = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        bior = new javax.swing.JCheckBox();
        phyr = new javax.swing.JCheckBox();
        reng = new javax.swing.JTextField();
        Srmath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbio.setEditable(false);
        rbio.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rbio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        rphy.setEditable(false);
        rphy.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rphy.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Book List Of Science");

        engr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        engr.setText("English");
        engr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                engrMouseClicked(evt);
            }
        });

        Smathr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Smathr.setText("Math");
        Smathr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SmathrMouseClicked(evt);
            }
        });

        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bior.setText("Biology");
        bior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biorMouseClicked(evt);
            }
        });

        phyr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phyr.setText("Physics");
        phyr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phyrMouseClicked(evt);
            }
        });

        reng.setEditable(false);
        reng.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reng.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Srmath.setEditable(false);
        Srmath.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Srmath.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(phyr)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(rphy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(engr)
                            .addComponent(Smathr)
                            .addComponent(bior))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Srmath, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reng, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(222, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reng, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Smathr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Srmath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phyr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rphy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void engrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_engrMouseClicked
        // TODO add your handling code here:
        if (engr.isSelected()){
            reng.setText("ENGLISH");
        }
        else
        reng.setText(null);
    }//GEN-LAST:event_engrMouseClicked

    private void SmathrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmathrMouseClicked
        // TODO add your handling code here:
        if (Smathr.isSelected()){
            Srmath.setText("MATH");
        }
        else
        Srmath.setText(null);
    }//GEN-LAST:event_SmathrMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String a = reng.getText();
        String b = Srmath.getText();
        String c = rbio.getText();
        String d = rphy.getText();
        
        if ((a.isEmpty()) && (b.isEmpty()) && (c.isEmpty()) && (d.isEmpty())){
            JOptionPane.showMessageDialog(null, "Please select a one", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
           new ReturnDateS().setVisible(true);
        dispose(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void biorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biorMouseClicked
        // TODO add your handling code here:
        if (bior.isSelected()){
            rbio.setText("BIOOLOGY");
        }
        else
        rbio.setText(null);
    }//GEN-LAST:event_biorMouseClicked

    private void phyrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phyrMouseClicked
        // TODO add your handling code here:
        if (phyr.isSelected()){
            rphy.setText("PHYSICS");
        }
        else
        rphy.setText(null);
    }//GEN-LAST:event_phyrMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookListScienceR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookListScienceR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookListScienceR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookListScienceR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookListScienceR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Smathr;
    public static javax.swing.JTextField Srmath;
    private javax.swing.JCheckBox bior;
    private javax.swing.JCheckBox engr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox phyr;
    public static javax.swing.JTextField rbio;
    public static javax.swing.JTextField reng;
    public static javax.swing.JTextField rphy;
    // End of variables declaration//GEN-END:variables
}
